version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    environment:
      FLASK_ENV: development  # Enable Flask auto-reload in development mode
